// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.DbMigrations.Migrations
{
 [DbContext(typeof(StoreContext))]
 [Migration("20230406212702_FirstInitialCreate")]
 partial class FirstInitialCreate
 {
  /// <inheritdoc />
  protected override void BuildTargetModel(ModelBuilder modelBuilder)
  {
#pragma warning disable 612, 618
   modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

   modelBuilder.Entity("API.Entity.Product", b =>
       {
        b.Property<int>("Id")
                     .ValueGeneratedOnAdd()
                     .HasColumnType("INTEGER");

        b.Property<string>("Name")
                     .HasColumnType("TEXT");

        b.HasKey("Id");

        b.ToTable("Products");
       });
#pragma warning restore 612, 618
  }
 }
}
